import type { Metadata } from 'next';

import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/Sidebar';

export const metadata: Metadata = {
    title: 'Backpack',
    description: 'Generated by create next app',
};

export default function MainLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider defaultOpen={false}>
            <AppSidebar />
            <main className="w-full h-screen container antialiased">{children}</main>
        </SidebarProvider>
    );
}
