import "./globals.css";

// import { ReactScan } from '@/components/react-scan';
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { DataStreamProvider } from "@/components/data-stream-provider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import TrpcProvider from "@/lib/trpc/client";
import { cn } from "@/lib/utils";

const geistSans = Geist({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Backpack",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<TrpcProvider>
			<html lang="en" suppressHydrationWarning>
				<body
					className={cn("bg-background font-sans antialiased", geistSans.className)}
					suppressHydrationWarning
				>
					<DataStreamProvider>
						<ThemeProvider attribute="class" defaultTheme="system" disableTransitionOnChange enableSystem>
							<ReactQueryDevtools initialIsOpen={false} />
							<Toaster position="top-center" richColors />
							{children}
						</ThemeProvider>
					</DataStreamProvider>
				</body>
			</html>
		</TrpcProvider>
	);
}
